# Generated by Django 6.0.7 on 2026-07-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='فاصله به\u200cروزرسانی (ثانیه)')),
                ('show_real_time_stats', models.BooleanField(default=True, verbose_name='نمایش آمار لحظه\u200cای')),
                ('default_date_range', models.IntegerField(default=30, verbose_name='بازه پیش\u200cفرض (روز)')),
                ('max_records_per_page', models.IntegerField(default=20, verbose_name='حداکثر رکورد در صفحه')),
                ('enable_export', models.BooleanField(default=True, verbose_name='فعال کردن خروجی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات داشبورد',
                'verbose_name_plural': 'تنظیمات داشبورد',
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام معیار')),
                ('metric_type', models.CharField(choices=[('appointments', 'نوبت\u200cها'), ('patients', 'بیماران'), ('doctors', 'پزشکان'), ('revenue', 'درآمد'), ('prescriptions', 'نسخه\u200cها')], max_length=20, verbose_name='نوع معیار')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مقدار')),
                ('change_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تغییر')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'معیار داشبورد',
                'verbose_name_plural': 'معیارهای داشبورد',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویجت')),
                ('widget_type', models.CharField(choices=[('statistics', 'آمار'), ('chart', 'نمودار'), ('table', 'جدول'), ('calendar', 'تقویم'), ('alerts', 'هشدارها')], max_length=20, verbose_name='نوع ویجت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='پیکربندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'ویجت داشبورد',
                'verbose_name_plural': 'ویجت\u200cهای داشبورد',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PatientDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='آخرین مراجعه')),
                ('next_appointment', models.DateTimeField(blank=True, null=True, verbose_name='نوبت بعدی')),
                ('pending_prescriptions', models.IntegerField(default=0, verbose_name='نسخه\u200cهای در انتظار')),
                ('unread_notifications', models.IntegerField(default=0, verbose_name='نوتیفیکیشن\u200cهای خوانده نشده')),
                ('health_score', models.IntegerField(default=0, verbose_name='امتیاز سلامت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='accounts.patientprofile', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'داشبورد بیمار',
                'verbose_name_plural': 'داشبوردهای بیماران',
            },
        ),
    ]
