# Generated by Django 6.0.7 on 2026-07-13 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='درآمد کل')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هزینه کل')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سود خالص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گزارش مالی',
                'verbose_name_plural': 'گزارش\u200cهای مالی',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PatientStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('total_patients', models.IntegerField(default=0, verbose_name='کل بیماران')),
                ('new_patients', models.IntegerField(default=0, verbose_name='بیماران جدید')),
                ('active_patients', models.IntegerField(default=0, verbose_name='بیماران فعال')),
            ],
            options={
                'verbose_name': 'آمار بیمار',
                'verbose_name_plural': 'آمار بیماران',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('total_appointments', models.IntegerField(default=0, verbose_name='کل نوبت\u200cها')),
                ('completed_appointments', models.IntegerField(default=0, verbose_name='نوبت\u200cهای تکمیل شده')),
                ('cancelled_appointments', models.IntegerField(default=0, verbose_name='نوبت\u200cهای لغو شده')),
                ('no_show_appointments', models.IntegerField(default=0, verbose_name='نوبت\u200cهای عدم حضور')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='accounts.doctorprofile', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'آمار نوبت',
                'verbose_name_plural': 'آمار نوبت\u200cها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گزارش')),
                ('report_type', models.CharField(choices=[('daily', 'گزارش روزانه'), ('weekly', 'گزارش هفتگی'), ('monthly', 'گزارش ماهانه'), ('yearly', 'گزارش سالانه'), ('custom', 'گزارش سفارشی')], max_length=20, verbose_name='نوع گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر فایل')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='پارامترها')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='تولید کننده')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
