# Generated by Django 6.0.7 on 2026-07-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-changed_at']},
        ),
    ]
