# Generated by Django 6.0.7 on 2026-07-13 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن قالب')),
                ('notification_type', models.CharField(choices=[('sms', 'پیامک'), ('email', 'ایمیل'), ('push', 'نوتیفیکیشن پوش'), ('in_app', 'نوتیفیکیشن داخلی')], max_length=20, verbose_name='نوع نوتیفیکیشن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'قالب نوتیفیکیشن',
                'verbose_name_plural': 'قالب\u200cهای نوتیفیکیشن',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20, verbose_name='شماره گیرنده')),
                ('message', models.TextField(verbose_name='متن پیامک')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('provider', models.CharField(default='default', max_length=50, verbose_name='ارائه دهنده')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه')),
            ],
            options={
                'verbose_name': 'لاگ پیامک',
                'verbose_name_plural': 'لاگ پیامک\u200cها',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('notification_type', models.CharField(choices=[('sms', 'پیامک'), ('email', 'ایمیل'), ('push', 'نوتیفیکیشن پوش'), ('in_app', 'نوتیفیکیشن داخلی')], default='in_app', max_length=20, verbose_name='نوع نوتیفیکیشن')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('failed', 'ناموفق'), ('read', 'خوانده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خواندن')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل گیرنده')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل گیرنده')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای اضافی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن',
                'verbose_name_plural': 'نوتیفیکیشن\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
